timeout: 20

expectedTitle: MAX

elements:
   english:
        findBy: id
        locator: en
   countries:
        findBy: xpath
        locator: //h3[text()="Canada"]
   product:    
        findBy: xpath
        locator: //a[@href='/products/']
   nutritionalImage:
        findBy: xpath
        locator: //img[@src='../images/product1.png']
   nutritionalContainer:
        findBy: xpath
        locator: (//div[@class="container"])[4]
   nutritionalText:
        findBy: xpath
        locator: //h3[text()="Nutritionals"]
   nutritionalLink:
        findBy: xpath
        locator: (//a[@href="/products/nutritionals/"])[1]
   learnMoreBtn:
        findBy: xpath
        locator: //a[@href='/products/nutritionals']
   image:
        findBy: xpath
        locator: (//div[@class="image-card"])[1]
   opportunityImage:
        findBy: xpath
        locator: //span[text()="Opportunity"]
   productsWithPurposeImage:
        findBy: xpath
        locator: //span[text()="PRODUCTS WITH PURPOSE"]
   maxGivesBackImage:
        findBy: xpath
        locator: //span[text()="MAX GIVES BACK"]
   helpCenterImage:
        findBy: xpath
        locator: //span[text()="HELP CENTER"]
   imageColor:
        findBy: xpath
        locator: (//div[@class="overlay-img bg-blue"])[2]
   weightManagementLink:
        findBy: xpath
        locator: //a[text()="Weight Management"]
   metaSwitchImage:
        findBy: xpath
        locator: //img[@src="https://maxintlmarketing.s3-us-west-2.amazonaws.com/images/product-pages/product-box-sidebar-metaSwitchBe.png"]
   languagedrpdwn:
        findBy: id
        locator: languages
   overlayImage:
        findBy: xpath
        locator: //div[@class="overlay-img bg-blue"]
   countrydrpdwn:
        findBy: id
        locator: countries
   foundationLink:
        findBy: xpath
        locator: //a[@href='/products/beauty/foundation/']
   buynowBtn:
        findBy: id
        locator: for_sponsor_button
   ournutritionalheading:
        findBy: xpath
        locator: //h3[text()="Our Nutritional Products"]
   cellgivity:
        findBy: xpath
        locator: //strong[text()="Cellgevity"]
   maxATP:
        findBy: xpath
        locator: //strong[text()="MaxATP"]
   maxNFuze:
        findBy: xpath
        locator: //strong[text()="Max N-Fuze"]
   maxONE:
        findBy: xpath
        locator: //strong[text()="MaxONE"]
   maxGXL:
        findBy: xpath
        locator: //strong[text()="MaxGXL"]
   max357:
        findBy: xpath
        locator: //strong[text()="Max357"]
   nutritionalOptions:
        findBy: xpath
        locator: //div[@class="simple-card h-100"]
   cellgivityheading:
        findBy: xpath
        locator: //h2[text()="Here are some other products you might like:"]
   subsign:
        findBy: xpath
        locator: (//li[@class="sub-prod-qty"])[1]
   addsign:
        findBy: xpath
        locator: (//li[@class="add-prod-qty"])[1]
   itemquantity:
        findBy: xpath
        locator: //li[@class="qty-product qty-product-id-NENUSA000102"]
   cellgivityLink:
        findBy: xpath
        locator: //a[@href="/products/cellgevity/"]
   maxgxlImage:
        findBy: xpath
        locator: //img[@class="prod-image-NENUSA000102"]
   cellgevityPlayButton:
        findBy: xpath
        locator: //div[@class="banner--play-icon center-it"]
   cellgevityOneMonthSupply:
        findBy: xpath
        locator: //img[@data-productid="NENUSA000602"]
   cellgevityOneMonthSupplyAddtoCartBtn:
        findBy: xpath
        locator: (//a[text()="Add to Cart"])[1]
   cartImage:
        findBy: xpath
        locator: //p[@class="cart-item-count"]
   cellgevityBrochure:
        findBy: xpath
        locator: //a[@title="Cellgevity Brochure"]
   cellgevityProductSheet:
        findBy: xpath
        locator: //a[@title="Cellgevity Product Sheet"]
   cellgevityIngredients:
        findBy: xpath
        locator: //a[@data-toggle="modal"]
   cellgevitySupplementfacts:
        findBy: xpath
        locator: //a[@title="Cellgevity Supplement Facts"]
   cellgevityOptionslist:
        findBy: xpath
        locator: //img[@class="width-100 margin-y-md img-round-border"]
   rightHandSymbol:
        findBy: xpath
        locator: //button[@class="slick-next slick-arrow"]
   leftHandSymbol:
        findBy: xpath
        locator: //button[@class="slick-prev slick-arrow"]
   cellgevityOtherProductsAddToCart:
        findBy: xpath
        locator: (//a[text()=" Add to Order "])[1]
   checkoutbtn:
        findBy: xpath
        locator: (//button[text()=" Continue to checkout "])[1]
   sureBtn:
        findBy: xpath
        locator: //button[text()=" Sure, I’d love to get a discount! "]
   notnowBtn: 
        findBy: id
        locator: btn-autoship-disagree
   cellgevityLinkText:
        findBy: xpath
        locator: //li[text()="Cellgevity"]
   nutritionallink:
        findBy: xpath
        locator: (//a[@href="/products/nutritionals/"])[3]
   margin:
        findBy: xpath
        locator: //ol[@class="breadcrumb margin-0"]
   ingredients:
        findBy: xpath
        locator: //img[@src="//s3-us-west-2.amazonaws.com/maxintlmarketing/images/product-pages/ingredients-icon.svg"]
   riboceine:
        findBy: xpath
        locator: //span[text()="Riboceine"]
   alphaliopicacid:
        findBy: xpath
        locator: //span[text()="Alpha Lipoic Acid"]
   brocolliseedextract:
        findBy: xpath
        locator: //span[text()="Broccoli Seed Extract"]
   turmericrootextract:
        findBy: xpath
        locator: //span[text()="Turmeric Root Extract"]
   resvertrol:
        findBy: xpath
        locator: //span[text()="Resveratrol"]
   grapeseedextract:
        findBy: xpath
        locator: //span[text()="Grape Seed Extract"]
   ingredientattribute:
        findBy: xpath
        locator: //a[@class="btn__arrow collapsed"]
   